language: node_js
node_js: node

jobs:
  include:
    - stage: Deploy
      install:
        - npm install --save-dev vuepress
      script:
        - npm run docs:build
      after_success:
        - mv README.md LICENSE docs/.vuepress/dist
      deploy:
        skip-cleanup: true
        provider: pages
        github-token: $GITHUB_TOKEN
        repo: Vladislav-Lyuminarskiy-websites/Web-course-website
        target-branch: master
        local-dir: docs/.vuepress/dist
        on:
          branch: master
